"""Export Phasor's palette to the user's GTK and Qt theme configuration."""

from __future__ import annotations

import hashlib
import os
import tempfile
from pathlib import Path
from typing import Any


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", "~/.config")).expanduser()


def _data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser()


def _write(path: Path, content: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def _set_ini(path: Path, section: str, values: dict[str, str]) -> None:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        lines = []
    heading = f"[{section}]"
    start = next((i for i, line in enumerate(lines) if line.strip() == heading), -1)
    if start < 0:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append(heading)
        start = len(lines) - 1
    end = next((i for i in range(start + 1, len(lines)) if lines[i].lstrip().startswith("[")), len(lines))
    remaining = dict(values)
    for i in range(start + 1, end):
        stripped = lines[i].lstrip()
        key, separator, _value = stripped.partition("=")
        if separator and key in remaining:
            lines[i] = f"{key}={remaining.pop(key)}"
    for key, value in remaining.items():
        lines.insert(end, f"{key}={value}")
        end += 1
    _write(path, "\n".join(lines).rstrip() + "\n")


def _rgb(value: str) -> tuple[int, int, int]:
    color = value.lstrip("#")
    return tuple(int(color[index:index + 2], 16) for index in (0, 2, 4))


def _csv_color(value: str) -> str:
    return ",".join(str(channel) for channel in _rgb(value))


def _contrast_foreground(value: str) -> str:
    red, green, blue = _rgb(value)
    luminance = (red * 299 + green * 587 + blue * 114) / 1000
    return "#101215" if luminance >= 150 else "#ffffff"


def _qt_palette(dark: bool, accent: str) -> str:
    window = "#202326" if dark else "#f3f5f8"
    base = "#171a1e" if dark else "#ffffff"
    button = "#292d33" if dark else "#e8ecf2"
    alternate = "#252a31" if dark else "#e9edf3"
    text = "#f0f2f5" if dark else "#1b2028"
    muted = "#a4aab6" if dark else "#596575"
    shadow = "#101215" if dark else "#aeb7c2"
    light = "#414751" if dark else "#ffffff"
    mid = "#353a43" if dark else "#c4ccd6"
    roles = [text, button, light, mid, shadow, mid, text, "#ffffff" if dark else "#000000", text, base, window, shadow, accent, _contrast_foreground(accent), "#78b9ff" if dark else "#1769aa", "#c3a0e6" if dark else "#7040a0", alternate, "#000000", base, text, muted, accent]
    return ", ".join(roles)


def _gtk_css(dark: bool, accent: str) -> str:
    bg = "#202326" if dark else "#f3f5f8"
    base = "#171a1e" if dark else "#ffffff"
    raised = "#292d33" if dark else "#e8ecf2"
    foreground = "#f0f2f5" if dark else "#1b2028"
    muted = "#a4aab6" if dark else "#596575"
    border = "#414751" if dark else "#d5dbe3"
    return f"""/* Generated by Phasor. Changes are replaced when the Phasor palette changes. */
@define-color theme_bg_color {bg};
@define-color theme_base_color {base};
@define-color theme_fg_color {foreground};
@define-color theme_text_color {foreground};
@define-color theme_selected_bg_color {accent};
@define-color theme_selected_fg_color {_contrast_foreground(accent)};
@define-color phasor_accent {accent};
* {{ color: {foreground}; caret-color: {accent}; }}
window, dialog, popover, menu {{ background-color: {bg}; color: {foreground}; }}
button, entry, spinbutton, dropdown, combobox, notebook, headerbar, toolbar {{
  background-color: {raised}; color: {foreground}; border: 1px solid {border}; border-radius: 3px;
}}
button:hover, entry:focus, button:checked {{ border-color: {accent}; }}
selection, *:selected {{ background-color: {accent}; color: {_contrast_foreground(accent)}; }}
"""


def _apply_gtk(config: Path, dark: bool, accent: str) -> None:
    css = _gtk_css(dark, accent)
    for version in ("gtk-3.0", "gtk-4.0"):
        directory = config / version
        _write(directory / "phasor.css", css)
        gtk_css = directory / "gtk.css"
        try:
            contents = gtk_css.read_text(encoding="utf-8")
        except FileNotFoundError:
            contents = ""
        marker = "/* Phasor theme import */"
        import_line = f"@import 'phasor.css'; {marker}"
        lines = [line for line in contents.splitlines() if marker not in line]
        lines.append(import_line)
        _write(gtk_css, "\n".join(lines).rstrip() + "\n")
        _set_ini(directory / "settings.ini", "Settings", {
            "gtk-application-prefer-dark-theme": "true" if dark else "false",
        })

    gtk2 = config.parent / ".gtkrc-2.0"
    try:
        contents = gtk2.read_text(encoding="utf-8")
    except FileNotFoundError:
        contents = ""
    start_marker = "# Phasor theme start"
    end_marker = "# Phasor theme end"
    start = contents.find(start_marker)
    end = contents.find(end_marker, start + len(start_marker)) if start >= 0 else -1
    if start >= 0 and end >= 0:
        contents = contents[:start] + contents[end + len(end_marker):]
    bg = "#202326" if dark else "#f3f5f8"
    fg = "#f0f2f5" if dark else "#1b2028"
    base = "#171a1e" if dark else "#ffffff"
    text = "# Phasor theme start\n"
    selected_text = _contrast_foreground(accent)
    text += f'gtk_color_scheme = "bg_color:{bg};fg_color:{fg};base_color:{base};text_color:{fg};selected_bg_color:{accent};selected_fg_color:{selected_text}"\n'
    text += 'style "phasor-colors" {\n'
    text += f'  bg[NORMAL] = "{bg}"\n'
    text += f'  fg[NORMAL] = "{fg}"\n'
    text += f'  base[NORMAL] = "{base}"\n'
    text += f'  text[NORMAL] = "{fg}"\n'
    text += f'  bg[SELECTED] = "{accent}"\n'
    text += f'  fg[SELECTED] = "{selected_text}"\n}}\nwidget_class "*" style "phasor-colors"\n# Phasor theme end'
    _write(gtk2, contents.rstrip() + ("\n\n" if contents.strip() else "") + text + "\n")


def _apply_qt(config: Path, data: Path, dark: bool, accent: str) -> None:
    bg = "#202326" if dark else "#f3f5f8"
    base = "#171a1e" if dark else "#ffffff"
    button = "#292d33" if dark else "#e8ecf2"
    text = "#f0f2f5" if dark else "#1b2028"
    muted = "#a4aab6" if dark else "#596575"
    border = "#414751" if dark else "#d5dbe3"
    selected_text = _contrast_foreground(accent)
    palette = _qt_palette(dark, accent)
    scheme = """[General]
Name=Phasor
Color=\"{bg}\"
Name[en_US]=Phasor

[Colors:Window]
BackgroundNormal={bg}
BackgroundAlternate={raised}
ForegroundNormal={text}
ForegroundInactive={muted}
ForegroundActive={accent}
DecorationFocus={accent}
DecorationHover={accent}
ForegroundLink={link}
ForegroundVisited={visited}
ForegroundNegative=#ed8796
ForegroundNeutral=#eed49f
ForegroundPositive=#a6da95

[Colors:Button]
BackgroundNormal={button}
BackgroundAlternate={raised}
ForegroundNormal={text}
ForegroundInactive={muted}
ForegroundActive={accent}
DecorationFocus={accent}
DecorationHover={accent}

[Colors:View]
BackgroundNormal={base}
BackgroundAlternate={raised}
ForegroundNormal={text}
ForegroundInactive={muted}
ForegroundActive={accent}
DecorationFocus={accent}

[Colors:Selection]
BackgroundNormal={accent}
BackgroundAlternate={accent}
ForegroundNormal={selected_text}
ForegroundInactive={selected_text}
ForegroundActive={selected_text}
DecorationFocus={accent}

[Colors:Tooltip]
BackgroundNormal={button}
ForegroundNormal={text}

[KDE]
widgetStyle=Breeze
""".format(
        bg=bg, base=base, button=button, raised="#252a31" if dark else "#e9edf3",
        text=text, muted=muted, accent=accent, selected_text=selected_text,
        link="#78b9ff" if dark else "#1769aa", visited="#c3a0e6" if dark else "#7040a0",
    )
    scheme_path = data / "color-schemes" / "Phasor.colors"
    _write(scheme_path, scheme)
    digest = hashlib.sha1(scheme.encode("utf-8")).hexdigest()
    _set_ini(config / "kdeglobals", "General", {"ColorScheme": "Phasor", "ColorSchemeHash": digest, "AccentColor": _csv_color(accent)})

    qt_values = {
        "Palette\\active": palette,
        "Palette\\inactive": palette,
        "Palette\\disabled": _qt_palette(dark, border),
    }
    _set_ini(config / "Trolltech.conf", "qt", qt_values)
    _set_ini(Path.home() / ".qt" / "qtrc", "qt", qt_values)


def apply_universal_theme(theme: dict[str, Any]) -> None:
    """Apply theme colors in GTK 2/3/4 and Qt 3/4/KDE user-level formats."""
    requested = str(theme.get("theme", "dark"))
    dark = requested != "light"
    if requested == "system":
        gtk3_settings = _config_home() / "gtk-3.0" / "settings.ini"
        try:
            setting = next(line.partition("=")[2].strip().lower() for line in gtk3_settings.read_text().splitlines() if line.startswith("gtk-application-prefer-dark-theme="))
            dark = setting == "true"
        except (OSError, StopIteration):
            pass
    accent = str(theme.get("accent", "#8bd5ca"))
    _apply_gtk(_config_home(), dark, accent)
    _apply_qt(_config_home(), _data_home(), dark, accent)
